// ============================================================
// Exporters — turn pipeline results into shareable artifacts
// (Markdown PRD, Gherkin .feature files). Pure functions, no React.
// ============================================================

import type { Requirement, TestCase, VersionPlanItem } from "./types";

/**
 * Build a Markdown PRD document from pipeline results.
 * Includes executive summary, version plan, and full requirement details
 * with traceability back to findings and source reviews.
 */
export function buildPRDMarkdown(opts: {
  appName?: string;
  executiveSummary?: string;
  versionPlan?: VersionPlanItem[];
  requirements?: Requirement[];
}): string {
  const { appName, executiveSummary, versionPlan, requirements = [] } = opts;
  const lines: string[] = [];
  const date = new Date().toISOString().split("T")[0];

  lines.push(`# 产品需求文档 (PRD)${appName ? ` — ${appName}` : ""}`);
  lines.push("");
  lines.push(`> 由 App Review Insights 自动生成 · ${date}`);
  lines.push("");

  if (executiveSummary) {
    lines.push("## 执行摘要");
    lines.push("");
    lines.push(executiveSummary);
    lines.push("");
  }

  if (versionPlan && versionPlan.length > 0) {
    lines.push("## 版本规划");
    lines.push("");
    for (const v of versionPlan) {
      lines.push(`### ${v.version} — ${v.theme}`);
      lines.push("");
      lines.push(`> ${v.rationale}`);
      lines.push("");
      lines.push(`**包含需求** (${v.requirementTitles.length} 条):`);
      for (const t of v.requirementTitles) {
        lines.push(`- ${t}`);
      }
      lines.push("");
    }
  }

  if (requirements.length > 0) {
    lines.push("## 需求详情");
    lines.push("");
    const byVersion = new Map<string, Requirement[]>();
    for (const req of requirements) {
      const v = req.version || "未规划";
      const list = byVersion.get(v) || [];
      list.push(req);
      byVersion.set(v, list);
    }
    for (const [version, reqs] of byVersion) {
      lines.push(`### ${version}`);
      lines.push("");
      for (const req of reqs) {
        lines.push(`#### ${req.id} [${req.priority}] ${req.title}`);
        lines.push("");
        if (req.isAssumption) {
          lines.push(
            "> ⚠ **假设需求** — 缺乏充分的用户证据支撑，建议开发前进行用户验证。"
          );
          lines.push("");
        }
        lines.push(req.description);
        lines.push("");
        lines.push(
          `**来源发现**: ${req.sourceFindingIds.join(", ") || "无"}`
        );
        const reviewIds = req.sourceReviewIds;
        lines.push(
          `**来源评论**: ${reviewIds.length} 条${
            reviewIds.length > 0
              ? ` (${reviewIds.slice(0, 5).join(", ")}${reviewIds.length > 5 ? ", ..." : ""})`
              : ""
          }`
        );
        lines.push("");
        lines.push("**验收标准**:");
        req.acceptance.forEach((a, i) => {
          lines.push(`${i + 1}. ${a}`);
        });
        lines.push("");
      }
    }
  }

  return lines.join("\n");
}

/**
 * Build Gherkin .feature content from test cases.
 * Each requirement becomes a Feature; each test case becomes a Scenario.
 * Steps are assumed to already follow Given/When/Then phrasing.
 * Output is Cucumber-compatible.
 */
export function buildGherkinFeatures(opts: {
  testCases?: TestCase[];
  requirements?: Requirement[];
}): string {
  const { testCases = [], requirements = [] } = opts;
  const reqMap = new Map(requirements.map((r) => [r.id, r]));

  const byReq = new Map<string, TestCase[]>();
  for (const tc of testCases) {
    const list = byReq.get(tc.requirementId) || [];
    list.push(tc);
    byReq.set(tc.requirementId, list);
  }

  const lines: string[] = [];
  const date = new Date().toISOString().split("T")[0];
  lines.push(`# Generated by App Review Insights · ${date}`);
  lines.push(
    `# ${testCases.length} test cases across ${byReq.size} requirements`
  );
  lines.push("");

  for (const [reqId, cases] of byReq) {
    const req = reqMap.get(reqId);
    const reqTitle = req?.title || "(unknown requirement)";
    lines.push(`Feature: ${reqId} ${reqTitle}`);
    if (req) {
      lines.push(`  Priority: ${req.priority}`);
      if (req.sourceFindingIds.length > 0) {
        lines.push(`  Source findings: ${req.sourceFindingIds.join(", ")}`);
      }
      if (req.sourceReviewIds.length > 0) {
        const ids = req.sourceReviewIds;
        lines.push(
          `  Source reviews: ${ids.slice(0, 10).join(", ")}${ids.length > 10 ? ", ..." : ""}`
        );
      }
    }
    lines.push("");

    for (const tc of cases) {
      lines.push(`  Scenario: ${tc.id} ${tc.title}`);
      lines.push(`    # Priority: ${tc.priority}`);
      for (const step of tc.steps) {
        lines.push(`    ${step}`);
      }
      lines.push(`    # Expected: ${tc.expectedResult}`);
      if (tc.sourceReviews.length > 0) {
        lines.push(`    # Source reviews: ${tc.sourceReviews.join(", ")}`);
      }
      lines.push("");
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Trigger a client-side text file download.
 */
export function downloadText(
  filename: string,
  content: string,
  mime = "text/plain"
): void {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
